#!/bin/bash
#module containing functions called from cylon package
#Functions: checkinputFunc, DisplayFunc.
# exitHandlerFunc, HelpFunc, msgFunc, readconfigFunc, weatherFunc

#FUNCTION HEADER
# NAME : msgFunc
# DESCRIPTION :   prints to screen
#prints line, text and anykey prompts, 
# INPUTS : $1 process name $2 text input
# PROCESS :[1]  print line [2] anykey prompt
# [3] print text  "green , red ,blue , norm yellow and highlight" ,                       
function msgFunc
{
	case "$1" in 
	
		line) #print blue horizontal line of =
			printf '\033[36;1m%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
			msgFunc norm
		;;
		anykey) #any key prompt, appends second text input to prompt
		    printf '%s' "${GREEN}" 
			read -n 1 -r -s -p "Press any key to continue $2"
			printf '%s\n' "${NORMAL}"
		;;
		
		#print passed text string
		green) printf '%s\n' "${GREEN}$2${NORMAL}" ;;
		red) printf '%s\n' "${RED}$2${NORMAL}" ;;
		blue) printf '%s\n' "${BLUE}$2${NORMAL}" ;;
		yellow)printf '%s\n' "${YELLOW}$2${NORMAL}" ;;
		highlight)printf '%s\n' "${HL}$2${NORMAL}" ;;
		
		norm) #print normal text colour
			if [ "$2" = "" ]
				then
				#just change colour to norm if no text sent
					printf '%s' "${NORMAL}"
				return
			fi
			printf '%s\n' "${NORMAL}$2" ;;
			
		*) #for development catah typos
			printf '%s\n' "ERROR unknown input to msgFunc"
			 ;;
	esac
}


#FUNCTION HEADER
# NAME :  exitHandlerFunc 
# DESCRIPTION: error handler deal with user 
#exists and path not found errors and internet failure 
# INPUTS:  $2 text of internet site down or filename
# PROCESS : exitout DEST 1-6 netdown or file error
function exitHandlerFunc
{
	#double square brackets without use of quotes on matching pattern 
	#for glob support
	if [[ "$1" = DEST* ]]
	then
		msgFunc red "Path not found to Destination directory"
	fi
	case "$1" in
			exitout) msgFunc norm "";;
			DEST1) msgFunc norm "$Destination1" ;;
			DEST2) msgFunc norm "$Destination2" ;;
			DEST3) msgFunc norm "$DEST3" ;;
			DEST4) msgFunc red "Path not found to directory"  ;;
			DEST5) msgFunc norm "$DEST5" ;;
			DEST6) msgFunc norm "$DEST6" ;;
			netdown) msgFunc red "Internet connectivity test to $2 failed" ;;
			fileerror) msgFunc red "File error $2"  ;;
			*) msgFunc yellow "unknown input to error handler";;
	 esac
	msgFunc yellow "Goodbye $USER!"
	msgFunc anykey "and exit."
	if [ "$1" = "exitout" ]
	then
		#non-error exit
		exit 0
	fi 
	exit 1
}

#FUNCTION HEADER
# NAME : DisplayFunc
# DESCRIPTION : Function to display main menu
function DisplayFunc
{
msgFunc blue "Main Menu:"
	local choiceMainVar
	local optionsMArr=(
	"pacman" "$(checkPacFunc cower NOMES)" \
	"$(checkPacFunc pacaur NOMES)" "System Update" "System Maintenance" \
	"System backup" "System Security" "Network Maintenance" \
	"xterm terminal" "View/Edit config file"\
	  "System information" "Cylon information" "Weather" "Exit"\
	)
	select choiceMainVar in "${optionsMArr[@]}"
	do
	case "$choiceMainVar" in
			"${optionsMArr[0]}")   #pacman update
				PacmanFunc
			;;
			"${optionsMArr[1]}") #cower AUR helper
				CowerFunc
			;;
			"${optionsMArr[2]}") #pacaur AUR helper
				pacaurFunc
			;;
			"${optionsMArr[3]}") #full system update.
				updateFunc
			;;
			"${optionsMArr[4]}") #system maintenance
				SystemMaintFunc 
			;;
			"${optionsMArr[5]}")  #Full system backup
				SystemBackFunc 
			;;
			"${optionsMArr[6]}")  #System security
				SystemSecFunc "$@"
			;;
			"${optionsMArr[7]}")  # network utiltes
				networkFunc
			;;
			"${optionsMArr[8]}")  # open a terminal
				xterm -e "cd $DEST3  && /bin/bash"
				msgFunc anykey
			;;
			"${optionsMArr[9]}")   #config file edit or view
				readconfigFunc "USERCALL"
			;;
			"${optionsMArr[10]}") #system info
				HelpFunc "SYS"
			;;
			"${optionsMArr[11]}")  # cylon info and cat readme file to screen 
				HelpFunc "HELP"
			;;
			"${optionsMArr[12]}")  # 3 day forecast weather
				WeatherFunc
			;;
			*)#exit
				exitHandlerFunc exitout 
			;;
	esac
	break
	done

}

#FUNCTION HEADER
# NAME :            HelpFunc
# DESCRIPTION :     two sections one prints various system information the
# other cylon information and the installed readme file
# INPUTS : $1 process name either HELP or SYS    
# OUTPUTS : n/a
# PROCESS :[1] HELP =cylon info [2] SYS   =system info
function HelpFunc 
{
clear
if ! checkPacFunc cower
	then
	msgFunc anykey 
	return
fi
if ! checkPacFunc arch-audit 
	then
	msgFunc anykey 
	return
fi
clear
msgFunc line
	if [ "$1" = "HELP" ]
				then
				msgFunc green "Cylon information and readme.md file  display." 
				msgFunc line 
				#Program details print
				cat <<-EOF
				Cylon is an Arch Linux maintenance CLI program written in Bash script.
				This program provides numerous tools to Arch Linux users to carry 
				out updates, maintenance, system checks, backups and more. 
				EOF
				msgFunc norm "Written by G.Lyons, Reports to  <glyons66@hotmail.com>"
				msgFunc norm "AUR package name = cylon, at aur.archlinux.org by glyons."
				msgFunc norm "Version=$(pacman -Qs cylon | head -1 | cut -c 7-20)"
				msgFunc norm "Cylon program location = $(which cylon)"
				msgFunc norm "Cylon modules for functions = /usr/lib/cylon/modules/*"
				msgFunc norm "Folder for Cylon output data = $DEST3"
				msgFunc norm "Location of cylonCfg.conf = $DEST5"
				msgFunc norm "Location of readme.md changlog.md = $DEST6"
				msgFunc norm "Location of License.md = /usr/share/licenses/cylon"
				msgFunc norm "Man page, Desktop entry and icon also installed"
				msgFunc anykey "and check which dependencies are installed"
				clear
				msgFunc norm " "
				msgFunc green "Dependencies"
				#dialog   needed to generate GUI menus
				checkPacFunc dialog  "NOTE: non-optional"
				#cower   needed to generate GUI menus
				checkPacFunc expac  "NOTE: non-optional"
				#cower  (optional) – AUR package for AUR work
				checkPacFunc cower "NOTE: AUR package"
				#gdrive  (optional) – AUR package for google drive backup
				checkPacFunc gdrive "NOTE: AUR package"
				#lostfiles (optional) – AUR package for finding lost files
				checkPacFunc lostfiles "NOTE: AUR package"
				#pacaur (optional – AUR package for AUR work
				checkPacFunc pacaur  "NOTE: AUR package"
				#arch-audit(optional) - Arch CVE Monitoring Team data
				checkPacFunc arch-audit 
				#rmlint (optional) – Finds lint and other unwanted
				checkPacFunc rmlint
				#rkhunter (optional) – finds root kits malware
				checkPacFunc rkhunter
				#gnu-netcat (optional) – used for checking network
				checkPacFunc gnu-netcat "NOTE: No need if using openbsd-netcat"
				#openbsd-netcat(optional) – used for checking network
				checkPacFunc openbsd-netcat "NOTE: No need if using gnu-netcat"
				#clamav  (optional) – used for finding malware
				checkPacFunc clamav
				#bleachbit  (optional) – used for system clean
				checkPacFunc bleachbit 
				#ccrypt (optional) – Encrypt and decrypt files
				checkPacFunc ccrypt
				#rsync (optional) – backup utility
				checkPacFunc rsync
				#lynis (optional) – system auditor
				checkPacFunc lynis
				#inxi (optional) – CLI system information script 
				checkPacFunc inxi
				#htop (optional) – Command line system information script 
				checkPacFunc htop
				#wavemon (optional) – wireless network monitor 
				checkPacFunc wavemon
				#speedtest-cli (optional) – testing internet bandwidth
				checkPacFunc speedtest-cli
					local choiceRmVar=""
					msgFunc green "Do you want to view readme? [Y/n]"
					read -r choiceRmVar
							if [ "$choiceRmVar" != "n" ]
								then
									msgFunc line
									msgFunc green "Displaying cylonReadme.md file at $DEST6"
									cd "$DEST6"  || exitHandlerFunc DEST6
									more Readme.md 
									msgFunc green "Done!" 
									msgFunc line
									msgFunc anykey
							fi
				clear
				return
			fi
msgFunc green "System Information display"
msgFunc line
msgFunc norm  #set colour back
msgFunc norm "Uptime = $(uptime -p)"
msgFunc norm "Operating System + Kernal = $(uname -mosr)"
msgFunc norm "Network node name = $(uname -n)"
msgFunc norm "Screen Resolution = $(xrandr |grep "\*" | cut -c 1-15)"
msgFunc norm "CPU $(grep name /proc/cpuinfo  | tail -1)"
mem=($(awk -F ':| kB' '/MemTotal|MemAvail/ {printf $2}' /proc/meminfo))
memused="$((mem[0] - mem[1]))"
memused="$((memused / 1024))"
memtotal="$((mem[0] / 1024))"
memory="${memused}MB / ${memtotal}MB"
msgFunc norm "RAM used/total = ($memory)"
msgFunc green "Package Information"
msgFunc norm "All installed packages: $(pacman -Q | wc -l)" 
msgFunc norm "All native packages: $(pacman -Qn | wc -l)" 
msgFunc norm "All explicitly installed packages: $(pacman -Qe | wc -l)" 
msgFunc norm "ALL explicitly installed native packages that are"
msgFunc norm "not direct or optional dependencies: $(pacman -Qqent | wc -l)"
msgFunc norm "All explicitely installed pkgs not base/base-devel grps: \
$(comm -23 <(pacman -Qeq | sort) <(pacman -Qgq base base-devel | sort) | wc -l ) "
msgFunc norm "All foreign installed packages: $(pacman -Qm | wc -l)"
msgFunc norm "All foreign explicitly installed packages: $(pacman -Qme | wc -l)"
msgFunc green "Accessing archlinux.org Network Database...."
msgFunc norm   "Number of Pacman updates ready: $(checkupdates | wc -l)" 
msgFunc norm "Number of updates for installed AUR packages ready: $(cower -u | wc -l)"
msgFunc norm "Number of upgradable Arch-audit vulnerable packages: $(arch-audit -qu | wc -l)"
msgFunc anykey 
clear
}

#FUNCTION HEADER
# NAME :           readconfigFunc
# DESCRIPTION:read the config file into program if not there   
#use hardcoded defaults config file is for paths for backup function
#Called when needed by program also can be called by user option or main menu
# passed USERCALL
# INPUTS $1 USERCALL when called by user
# OUTPUTS : sets paths for backup function 
# PROCESS : read $DEST5/cylonCfg.conf
#NOTES :   file is optional       
function readconfigFunc
{
	#check input if called by user from menu or option
	if [ "$1" = "USERCALL" ]
		then
		cd "$DEST5"  || exitHandlerFunc DEST5
		if [ -f "$DEST5/cylonCfg.conf" ] 
			then
				local choiceCCVar
				msgFunc green "Do you want to edit or view? [e/V]"
				read -r choiceCCVar
				if [ "$choiceCCVar" = "e" ]
					then
						nano  "$DEST5/cylonCfg.conf" || exitHandlerFunc fileerror "$DEST5/cylonCfg.conf"
						clear
						msgFunc green "Exiting config file edit option"
						msgFunc anykey "and exit cylon."
						exit 0
					else
					msgFunc green  "Custom paths read from file"
					cat "$DEST5/cylonCfg.conf" || exitHandlerFunc fileerror "$DEST5/cylonCfg.conf"
					msgFunc green "Done!"
					msgFunc anykey
					return
				fi
			else
				exitHandlerFunc fileerror "$DEST5/cylonCfg.conf"
		fi
	fi
	
	#read cylon.conf for system back up paths 
	msgFunc green "Reading config file cylonCfg.conf at:-"
	msgFunc norm "$DEST5"
	#check if file there if not use defaults.
	if [ ! -f "$DEST5/cylonCfg.conf" ]
		then
		msgFunc red "No config found: Use the default hardcoded paths"
		#path for an internal hard drive backup
		Destination1="/run/media/$USER/Linux_backup/foo"
		#path for an external hard drive backup
		Destination2="/run/media/$USER/iomega_320/foo"
		#default paths for gdrive sync uploads 
		gdriveSource1="$HOME/Documents"
		gdriveDest1="0B3_YYYfoo"
		gdriveSource2="$HOME/Pictures"
		gdriveDest2="0B3_XXXXfoo"
		gdriveSource3="$HOME/Videos"
		gdriveDest3="0B7_XXXXYYYfoo"
		gdriveSource4="$HOME/.config"
		gdriveDest4="0B1_XXXYYYfoo"
		#paths for rsync option
		rsyncsource="$HOME/"
		rsyncDest="/run/media/$USER/Linux_backup/foo"
		#ccyptfile
		myccfile="/foo/foo/XXXX"
		msgFunc green "Done!"
		return
	fi
	cd "$DEST5"  || exitHandlerFunc DEST5
	# shellcheck disable=SC1091
	source ./cylonCfg.conf || exitHandlerFunc fileerror "$DEST5/cylonCfg.conf"
	msgFunc green  "Custom paths read from file"
	cat ./cylonCfg.conf || exitHandlerFunc fileerror "$DEST5/cylonCfg.conf"
	msgFunc green "Done!"
}

#FUNCTION HEADER
# NAME :           checkinputFunc
# DESCRIPTION:CHECK INPUT OPTIONS from linux command line arguments passed to program on call
# INPUTS :  $1 user input option
#-v display version and exit
#-s display system info and exit
#-h display cylon info and exit 
#-c open config file for edit.
#-u update all
#-d run bleachbit default as set in GUI
#-b run the bleachbit function
function checkinputFunc
{
case "$1" in
	"");;
	-u|--update) #update system report 
		updateFunc
	;;
	-c|--config)
		readconfigFunc "USERCALL"
		;;
	-d|--default)
#Bleachbit system clean. Use the options set in the GUI
		msgFunc green "Bleachbit system clean"  
		msgFunc norm "Preset options see $HOME/.config/bleachbit/ or GUI "
		msgFunc anykey "To run bleachbit -c --preset"
		msgFunc norm  "Running bleachbit -c --preset"
		bleachbit -c --preset
		msgFunc green "Done!"
		;;
	-v|--version)
		msgFunc norm "$(pacman -Qs cylon)" 
		;;
	-s|--system)
		HelpFunc SYS
		;;
	-h|--help)
		HelpFunc HELP
		;;
	-b|--bleachbit)
		SystemCleanFunc
	;;
	-m|--maint)
		SystemMaintAutoFunc
	;;
	*) msgFunc yellow "Invalid option, Usage: -b -c -d -h -m -s -u -v"
	  msgFunc yellow "See readme.md for details at cylon -h "
	;;
esac
#was there a input if yes quit?
if [ -n "$1" ] 
	then
		exit 0 
fi
clear
}

#FUNCTION HEADER
# NAME : makeDirFunc
# DESCRIPTION :  makes a directory with time/date stamp and enters it
#Directory used for program output and backups. 
# INPUTS : $1 text is appended to name  $2 bit flag  to change dir or not
function makeDirFunc
{
			local dirVar=""
			#makes dirs for output appends passed text to name
			#check if coming from system backup other path 1 yes 0 no.
			if [ "$2" != 1 ]
				then 
				cd "$DEST3" || exitHandlerFunc DEST3
			fi
			dirVar=$(date +%H%M-%d%b%y)"$1"
			mkdir "$dirVar"
			cd "$dirVar" || exitHandlerFunc DEST4
			msgFunc norm "Directory for output made at:-"
			pwd	 
}

#FUNCTION HEADER
# NAME :  WeatherFunc
# DESCRIPTION:3 day weather forecast
function WeatherFunc
{
					msgFunc norm "3 day weather forecast by WTTR.IN"
					msgFunc norm "Type a City name, airport code, domain name or area code:-"
					local mycityVar=""
					read -r mycityVar		
					clear
					curl wttr.in/"$mycityVar"
					msgFunc anykey 
					clear
}

