#!/bin/bash
#Module containing functions called from cylon package
#Functions: RmLintFunc

#FUNCTION HEADER
# NAME :  RmLintFunc 
# DESCRIPTION: Function for crmlint - 
#find duplicate files and other space waste efficiently
# PROCESS : rmlint scan 
#NOTES :    needs rmlint installed
function RmLintFunc
{
	clear
	msgFunc green "Running rmlint"
cat <<-EOF
rmlint finds space waste and other broken things on your filesystem.
It then produces a report and a shellscript called rmlint.sh that 
contains readily prepared shell commands to remove duplicates and other 
finds. cylon wrapper  will scan, then optionally show report and then  
optionally execute the rmlint.sh.
EOF
	     #check rmlint is installed
            if ! checkPacFunc rmlint
				then
				msgFunc anykey 
				return
			fi
			local rmlintPathVar=""
			rmlintPathVar=$(dialog --title "Rmlint" --output-fd 1 --begin 1 1 --cancel-label "Exit" --title  "Select Directory path you wish to scan:" --dselect / 10 40)
			case $? in
				0)
					clear
				;;
				1)
					clear
					msgFunc yellow "Exit pressed."
					return
				;;
				255)
					clear
					msgFunc yellow "Esc pressed."
					return
				;;
			esac
			#read -r rmlintPath	            
		     cd "$rmlintPathVar" || exitHandlerFunc DEST4
			msgFunc norm " "
			msgFunc norm "\"$rmlintPathVar\" chosen directory."
			msgFunc line

			#menu for rmlint opton selection
			local choiceRMVar
			local optionsRMArr=("All" "badids, bi: Find bad UID, GID or files with both." \
			"badlinks, bl: Find bad symlinks pointing nowhere." \
			"emptydirs, ed: Find empty directories." \
			"emptyfiles, ef: Find empty files." \
			"nonstripped, ns: Find nonstripped binaries."\
			"duplicates, df: Find duplicate files."\
			"duplicatedirs, dd: Find duplicate directories."\
			"Return")

			msgFunc blue "Pick rmlint options for selected directory $rmlintPathVar"
			select  choiceRMVar in "${optionsRMArr[@]}"
			#check that paths exist and change path to DEST path
			do
			case "$choiceRMVar" in
			
			"${optionsRMArr[0]}")#all
			rmlint -g
			;;
			"${optionsRMArr[1]}")#badids, bi: Find bad UID, GID or files with both
			rmlint -g --types="+bi"
			;;
			"${optionsRMArr[2]}")#badlinks, bl: Find bad symlinks pointing nowhere
			rmlint -g --types="+bl"
			;;
			"${optionsRMArr[3]}")#emptydirs, ed: Find empty directories.
			rmlint -g --types="+ed"
			;;
			"${optionsRMArr[4]}")#emptyfiles, ef: Find empty files  
			rmlint -g --types="+ef"
			;;
			"${optionsRMArr[5]}")#nonstripped, ns: Find nonstripped binaries.
			rmlint -g --types="+ns"
			;;
			"${optionsRMArr[6]}")#duplicates, df: Find duplicate files.
			rmlint -g --types="+df"
			;;
			"${optionsRMArr[7]}")#duplicatedirs, dd: Find duplicate directories
			rmlint -g --types="+dd"
			;;
			*) #exit
			clear
			return 
			;;
			esac
			break
			done

			msgFunc green "Done!"
			msgFunc line
			msgFunc anykey
			#display the results file option? 
			local choiceRM2Var=""
			msgFunc green "Display results file  [Y/n]?"
			read -r choiceRM2Var
			if [ "$choiceRM2Var" != "n" ]
			then
				msgFunc green  "rmlint output file"
				more rmlint.json		
				msgFunc line
				msgFunc anykey
			fi
				#run the shell option?
				msgFunc green "Execute rmlint.sh file? press e or any key to quit [e/N]"
				msgFunc red "Warning rmlint.sh will change your system based on results of the previous scan"
			    local choiceRM3Var=""
			    read -r choiceRM3Var
					if [ "$choiceRM3Var" = "e" ]
					then
						msgFunc green  "running rmlint.sh output file"
						./rmlint.sh -d
					else
						msgFunc green "Done!"
						return
					fi
			msgFunc green "Done!"
}
