.TH CYLON "7" "March 2017" "1.0.1" "User Commands"

.SH NAME
cylon \- This script provides numerous tools to Arch Linux users.

.SH SYNOPSIS
.B cylon \fR[Optional Flags]

.SH DESCRIPTION
The goal was to create a script to do as much updates maintenance, 
backups and system checks in a single menu driven optional script 
Command line program for an Arch linux distro as possible.
This script provides numerous tools 
to Arch Linux users for updates, maintenance, system checks and backups.  

.SH ENVIRONMENT VARIABLES 
.TP
.B \ CYLONDEST 
example= export CYLONDEST="$HOME/.cache/cylon"  ,
Optional destination for program output.
Sets the output folder for downloads updates etc
if variable is not set or does not exist,, cylon uses default path at 
$HOME/Documents/Cylon

.TP
.B \ CYLON_CONFIG
example= export CYLON_CONFIG="$HOME/TEST/cylon/config"  ,
Optional destination for config file.
if variable is not set or does not exist,, cylon uses default path at 
$HOME/.config/cylon/cylonCfg.conf

.TP
.B \ CYLON_COLOR_OFF
example= export CYLON_COLOR_OFF="on"  ,
Optional destination for colour text output file.
if variable is not set or does not exist, cylon uses its default colour scheme 
if set no colour text.

.SH OPTIONS
.TP
.B \-c --config 
Opens the cylon config file for editing and exit
.TP
.B \-h --help 
Print cylon information and exit
.TP
.B \-s --system 
Print system information and exit
.TP
.B \-u --update 
Runs a full update report with option to execute and exit
.TP
.B \-d --default
Bleachbit system clean. Use the options set in the GUI/file
.TP
.B \-v --version 
Print version information and exit.
.TP
.B \-b --bleachbit 
Open bleachbit menu select options.
.TP
.B \-m --maint 
Run a Automatic system maintenance scan.
.TP
.B \-p --print
Print the package lists
.TP
.B \-l --lint 
Shortcut to open rmlint wrapper.
.TP
.B \-z --delete 
Display the AUR package removal dialog menu function.
.TP
.B \-r --rss 
Print arch news reader last four items
.TP
.B \-n --notify 
Desktop notifications with update information.

.SH CYLON FILES
.TP
.B \ 
/usr/bin/cylon (the shell script)
.TP
.B \ 
/usr/lib/cylon/modules (library functions)
.TP
.B \ 
/usr/share/doc/cylon/Readme.md
.TP
.B \ 
/usr/share/doc/cylon/changelog.md
.TP
.B \ 
/usr/share/licenses/cylon/License.md
.TP
.B \ 
/usr/share/man/man1/cylon.7
.TP
.B \ 
$HOME/.config/cylon/cylonCfg.conf (optional, user made, not installed)


.SH CONFIG FILE SETTINGS
.TP
.B \ Destination1="/foo/foo/" 
Backup path 1 destination
.TP
.B \ Destination2="/foo/foo3/" 
Backup path 2 destination
.TP
.B \ gdriveSource1="foo/foo" 
Source for Gdrive backup local Source path 1
.TP
.B \ gdriveSource2="foo/foo2" 
Source for Gdrive backup local Source path 2
.TP
.B \ gdriveSource3="foo/foo2" 
Source for Gdrive backup local Source path 3
.TP
.B \ gdriveDest1="foo123456789" 
Destination for Gdrive backup path 1 on google drive
is remote google drive  directory ID(see gdrive readme)
.TP
.B \ gdriveDest2="foo2123456789" 
Destination  for Gdrive backup path 2 on google drive
is remote google drive  directory ID(see gdrive readme)
.TP
.B \ gdriveDest3="foo2123456789" 
Destination  for Gdrive backup path 2 on google drive
is remote google drive  directory ID(see gdrive readme)
.TP
.B \ rsyncsource="$HOME/"
rsync backup source option
.TP
.B \ rsyncDest="/run/media/$USER/foo1/foo"
Backup path for rsync destination
.TP
.B \ myccfile="$HOME/"
default file path option for ccrypt
.TP
.B \ clamav_customdir="$HOME/.config/cylon/foo"
Custom path for clamavscan


.SH RETURN CODES
.IP \fB0\fR
Everything went well
.IP \fB1\fR
Error occured and  handled by exithandler function.

.SH OTHER
Most system output (logsfiles, backups, downloads and updates etc) 
is placed at below path , unless otherwise specified on screen
output folders are created with following syntax HHMM-DDMONYY-X where X
is output type i.e backup, update etc. 
This setting can be overwritten by environmental variable see above
.TP
.B $HOME/Documents/Cylon

.SH AUTHOR
Created by Gavin Lyons. glyons66@hotmail.com

.SH "SEE ALSO"
upstream repository https://github.com/gavinlyonsrepo/cylon
Cylon information page option in menu or -h includes depends 
installation check.
This manpage is a TRUNCATED version of the readme.md file.
Readme.md for FULL detailed list of menu options and functions
is displayed on cylon information page which is launched from menu or -h option

.SH REPORTING BUGS
If you should find a bug or any other query , 
please send a report 
to upstream repo https://github.com/gavinlyonsrepo/cylon
or mail glyons66@hotmail.com
Pull requests, suggestions for improvements and new features welcome.

.SH COPYRIGHT
Copyright (C) 2016 G Lyons 
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, see license.md for more details


.SH HISTORY
see changelog.md
